### ISSUE TITLE
clash with numpy version restricted by numba (

### ISSUE THREAD

**Issue by daniel-spies** [Just-Jia/ccNet#1]
Hi,

read the paper and seems like a great tool I'd like to test. whilst installing and loading like a charm in a new virtual environment, my standard environment that has as numpy restriction to <1.22 due to the numba module I can't import the ccnet module

```
File "<stdin>", line 1, in <module>
  File "/home/spies.daniel/.conda/envs/seurat/lib/python3.9/site-packages/ccnet/__init__.py", line 3, in <module>
    from .homology import *
  File "/home/spies.daniel/.conda/envs/seurat/lib/python3.9/site-packages/ccnet/homology.py", line 5, in <module>
    from ripser import ripser
  File "/home/spies.daniel/.conda/envs/seurat/lib/python3.9/site-packages/ripser/__init__.py", line 1, in <module>
    from .ripser import *
  File "/home/spies.daniel/.conda/envs/seurat/lib/python3.9/site-packages/ripser/ripser.py", line 34, in <module>
    from pyRipser import doRipsFiltrationDM as DRFDM
  File "ripser/pyRipser.pyx", line 1, in init pyRipser
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

whilst the installer does not state any numpy requirements maybe list these, or is there another workaround so that I could use ccnet in my main environment?

best
Daniel

**Comment by Just-Jia** [comment]
Hi, Daniel

I developed ccnet with python3.8. If you use conda, maybe you can create a new environment with python3.8 then activate, like 
```
conda create --name my_ccnet python=3.8 pip
conda activate my_ccnet
```
Then, install the dependencies and ccnet, like
```
pip install numpy, pandas, ripser, networkx, tqdm, leidenalg, scikit-network
pip install ccnet
```

hope it works.

**Comment by Just-Jia** [comment]
Hi, Daniel

I developed ccnet with python3.8. If you use conda, maybe you can create a new environment with python3.8 then activate, like 
```
conda create --name my_ccnet python=3.8 pip
conda activate my_ccnet
```
Then, install the dependencies and ccnet, like
```
pip install numpy, pandas, ripser, networkx, tqdm, leidenalg, scikit-network
pip install ccnet
```

hope it works. @daniel-spies

**Comment by daniel-spies** [comment]
Hi Jia

using a fresh environment works well, this I already tested, just e.g. to then immediately use other tools/modules afterwards I'd have to switch envs and reload etc. 

So having been tired I didn't pay full attention to the versions, a ripser module downgrade to v0.5.4 resolved this issue.
unless this version conflicts with some functions this issue can be closed, thanks for the fast reply!
