### ISSUE TITLE
networkx major update

### ISSUE THREAD

**Issue by AlePur** [Just-Jia/ccNet#2]
Hello.
First of all, thank for this amazing tool! And good example showcasing the usage. I noticed that since 2022, a new networkx major version has been released (3.0.0) which has breaking changes for this tool. The issue is the `from_numpy_matrix()` function, which has been removed. `pip install networkx==2.8.8` fixed it. I think it will be good for other people to know that this tool depends on networkx < 3.0.0; that is why I opened this issue.

**Comment by Just-Jia** [comment]
Thank you for your kind reminder. It has been a while since I last updated this repo. I'll consider solving the issue you mentioned and other outstanding things.  Thank you.
